//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VertAccount.TechLabsLib.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VertAccount.TechLabsLib.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CloseServer_ConnectionString_Description {
            get {
                return ResourceManager.GetString("CloseServer_ConnectionString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectionString.
        /// </summary>
        public static string CloseServer_ConnectionString_DisplayName {
            get {
                return ResourceManager.GetString("CloseServer_ConnectionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current open connection..
        /// </summary>
        public static string CloseServer_Description {
            get {
                return ResourceManager.GetString("CloseServer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Server.
        /// </summary>
        public static string CloseServer_DisplayName {
            get {
                return ResourceManager.GetString("CloseServer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CloseServer_Result_Description {
            get {
                return ResourceManager.GetString("CloseServer_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CloseServer_Result_DisplayName {
            get {
                return ResourceManager.GetString("CloseServer_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataOuput_BotName_Description {
            get {
                return ResourceManager.GetString("DataOuput_BotName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotName.
        /// </summary>
        public static string DataOuput_BotName_DisplayName {
            get {
                return ResourceManager.GetString("DataOuput_BotName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataOuput_Company_Description {
            get {
                return ResourceManager.GetString("DataOuput_Company_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string DataOuput_Company_DisplayName {
            get {
                return ResourceManager.GetString("DataOuput_Company_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataOuput_ConnectionString_Description {
            get {
                return ResourceManager.GetString("DataOuput_ConnectionString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string DataOuput_ConnectionString_DisplayName {
            get {
                return ResourceManager.GetString("DataOuput_ConnectionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataOuput_Description {
            get {
                return ResourceManager.GetString("DataOuput_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Ouput.
        /// </summary>
        public static string DataOuput_DisplayName {
            get {
                return ResourceManager.GetString("DataOuput_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataOuput_FilingPeriod_Description {
            get {
                return ResourceManager.GetString("DataOuput_FilingPeriod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilingPeriod.
        /// </summary>
        public static string DataOuput_FilingPeriod_DisplayName {
            get {
                return ResourceManager.GetString("DataOuput_FilingPeriod_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataOuput_LogsList_Description {
            get {
                return ResourceManager.GetString("DataOuput_LogsList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogsList.
        /// </summary>
        public static string DataOuput_LogsList_DisplayName {
            get {
                return ResourceManager.GetString("DataOuput_LogsList_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataOuput_OutputList_Description {
            get {
                return ResourceManager.GetString("DataOuput_OutputList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputList.
        /// </summary>
        public static string DataOuput_OutputList_DisplayName {
            get {
                return ResourceManager.GetString("DataOuput_OutputList_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataOuput_ResultText_Description {
            get {
                return ResourceManager.GetString("DataOuput_ResultText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultText.
        /// </summary>
        public static string DataOuput_ResultText_DisplayName {
            get {
                return ResourceManager.GetString("DataOuput_ResultText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetData_BotName_Description {
            get {
                return ResourceManager.GetString("GetData_BotName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotName.
        /// </summary>
        public static string GetData_BotName_DisplayName {
            get {
                return ResourceManager.GetString("GetData_BotName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetData_Company_Description {
            get {
                return ResourceManager.GetString("GetData_Company_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string GetData_Company_DisplayName {
            get {
                return ResourceManager.GetString("GetData_Company_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetData_ConnectionString_Description {
            get {
                return ResourceManager.GetString("GetData_ConnectionString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string GetData_ConnectionString_DisplayName {
            get {
                return ResourceManager.GetString("GetData_ConnectionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetData_Description {
            get {
                return ResourceManager.GetString("GetData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Data.
        /// </summary>
        public static string GetData_DisplayName {
            get {
                return ResourceManager.GetString("GetData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetData_FilingPeriod_Description {
            get {
                return ResourceManager.GetString("GetData_FilingPeriod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilingPeriod.
        /// </summary>
        public static string GetData_FilingPeriod_DisplayName {
            get {
                return ResourceManager.GetString("GetData_FilingPeriod_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetData_RefCode_Description {
            get {
                return ResourceManager.GetString("GetData_RefCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefCode.
        /// </summary>
        public static string GetData_RefCode_DisplayName {
            get {
                return ResourceManager.GetString("GetData_RefCode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetData_ResultDatatable_Description {
            get {
                return ResourceManager.GetString("GetData_ResultDatatable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultDatatable.
        /// </summary>
        public static string GetData_ResultDatatable_DisplayName {
            get {
                return ResourceManager.GetString("GetData_ResultDatatable_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetData_ResultText_Description {
            get {
                return ResourceManager.GetString("GetData_ResultText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultText.
        /// </summary>
        public static string GetData_ResultText_DisplayName {
            get {
                return ResourceManager.GetString("GetData_ResultText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PDFMerger_Description {
            get {
                return ResourceManager.GetString("PDFMerger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Merger.
        /// </summary>
        public static string PDFMerger_DisplayName {
            get {
                return ResourceManager.GetString("PDFMerger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PDFMerger_Path_Description {
            get {
                return ResourceManager.GetString("PDFMerger_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PDFMerger_Path_DisplayName {
            get {
                return ResourceManager.GetString("PDFMerger_Path_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PDFMerger_PDFFiles_Description {
            get {
                return ResourceManager.GetString("PDFMerger_PDFFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFFiles.
        /// </summary>
        public static string PDFMerger_PDFFiles_DisplayName {
            get {
                return ResourceManager.GetString("PDFMerger_PDFFiles_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PDFMerger_PDFOutputName_Description {
            get {
                return ResourceManager.GetString("PDFMerger_PDFOutputName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDFOutputName.
        /// </summary>
        public static string PDFMerger_PDFOutputName_DisplayName {
            get {
                return ResourceManager.GetString("PDFMerger_PDFOutputName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server_Category {
            get {
                return ResourceManager.GetString("Server_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Server_Connected_Description {
            get {
                return ResourceManager.GetString("Server_Connected_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Server_Connected_DisplayName {
            get {
                return ResourceManager.GetString("Server_Connected_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Server_ConnectionString_Description {
            get {
                return ResourceManager.GetString("Server_ConnectionString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string Server_ConnectionString_DisplayName {
            get {
                return ResourceManager.GetString("Server_ConnectionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Server_Database_Description {
            get {
                return ResourceManager.GetString("Server_Database_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Server_Database_DisplayName {
            get {
                return ResourceManager.GetString("Server_Database_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Server_Description {
            get {
                return ResourceManager.GetString("Server_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server_DisplayName {
            get {
                return ResourceManager.GetString("Server_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Server_Password_Description {
            get {
                return ResourceManager.GetString("Server_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Server_Password_DisplayName {
            get {
                return ResourceManager.GetString("Server_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Server_ServerAuthType_Description {
            get {
                return ResourceManager.GetString("Server_ServerAuthType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerAuthType.
        /// </summary>
        public static string Server_ServerAuthType_DisplayName {
            get {
                return ResourceManager.GetString("Server_ServerAuthType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Server_ServerName_Description {
            get {
                return ResourceManager.GetString("Server_ServerName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerName.
        /// </summary>
        public static string Server_ServerName_DisplayName {
            get {
                return ResourceManager.GetString("Server_ServerName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Server_UserName_Description {
            get {
                return ResourceManager.GetString("Server_UserName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string Server_UserName_DisplayName {
            get {
                return ResourceManager.GetString("Server_UserName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA Bot.
        /// </summary>
        public static string VABot_Category {
            get {
                return ResourceManager.GetString("VABot_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VerifyVersion_BotName_Description {
            get {
                return ResourceManager.GetString("VerifyVersion_BotName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotName.
        /// </summary>
        public static string VerifyVersion_BotName_DisplayName {
            get {
                return ResourceManager.GetString("VerifyVersion_BotName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VerifyVersion_BotVersion_Description {
            get {
                return ResourceManager.GetString("VerifyVersion_BotVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotVersion.
        /// </summary>
        public static string VerifyVersion_BotVersion_DisplayName {
            get {
                return ResourceManager.GetString("VerifyVersion_BotVersion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VerifyVersion_ConnectionString_Description {
            get {
                return ResourceManager.GetString("VerifyVersion_ConnectionString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string VerifyVersion_ConnectionString_DisplayName {
            get {
                return ResourceManager.GetString("VerifyVersion_ConnectionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VerifyVersion_Description {
            get {
                return ResourceManager.GetString("VerifyVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Version.
        /// </summary>
        public static string VerifyVersion_DisplayName {
            get {
                return ResourceManager.GetString("VerifyVersion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VerifyVersion_ResultText_Description {
            get {
                return ResourceManager.GetString("VerifyVersion_ResultText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultText.
        /// </summary>
        public static string VerifyVersion_ResultText_DisplayName {
            get {
                return ResourceManager.GetString("VerifyVersion_ResultText_DisplayName", resourceCulture);
            }
        }
    }
}
